export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS  = "LOGOUT_SUCCESS";

export const UPDATE_USER_INFORMATION = "UPDATE_USER_INFORMATION";
export const GET_USER = "GET_USER";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const ADD_USER = "ADD_USER";

export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_FULLFILLED = 'GET_SKILLS_FULLFILLED';
export const ADD_SKILL = 'ADD_SKILL';
export const SKILLS_WERE_CHECKED = 'SKILLS_WERE_CHECKED';

