export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS  = "LOGOUT_SUCCESS";

export const UPDATE_USER = "UPDATE_USER";
export const GET_USER = "GET_USER";
export const GET_USER_FULFILLED = "GET_USER_FULFILLED";
export const ADD_USER = "ADD_USER";

export const GET_SKILLS = 'GET_SKILLS';
export const GET_SKILLS_FULLFILLED = 'GET_SKILLS_FULLFILLED';
export const ADD_SKILL = 'ADD_SKILL';
export const DELETE_SKILL = 'DELETE_SKILL';
export const SKILLS_WERE_CHECKED = 'SKILLS_WERE_CHECKED';

export const GET_CERTIFICATIONS = 'GET_CERTIFICATIONS';
export const GET_CERTIFICATIONS_FULFILLED = 'GET_CERTIFICATIONS_FULFILLED';
export const ADD_CERTIFICATION = 'ADD_CERTIFICATION';
export const DELETE_CERTIFICATION = 'DELETE_CERTIFICATION';
export const EDIT_CERTIFICATION = 'EDIT_CERTIFICATION';


export const GET_EXPERIENCES = 'GET_EXPERIENCES';
export const GET_EXPERIENCES_FULLFILLED = 'GET_EXPERIENCES_FULFILLED';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const DELETE_EXPERIENCE = 'DELETE_EXPERIENCE';
export const EDIT_EXPERIENCE = 'EDIT_EXPERIENCE';


export const ADD_TEAM = 'ADD_TEAM';
export const GET_TEAM = 'GET_TEAM';
export const GET_ALL_TEAMS = 'GET_ALL_TEAMS';
export const GET_TEAM_FULFILLED = 'GET_TEAM_FULFILLED';
export const GET_ALL_TEAMS_FULFILLED = 'GET_ALL_TEAMS_FULFILLED';


export const GET_PROJECT = 'GET_PROJECT';
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_PROJECT_FULFILLED = 'GET_PROJECT_FULFILLED';


export const GET_TEAM_ROLES = 'GET_TEAM_ROLES';
export const ADD_ROLE_TO_TEAM = 'ADD_ROLE_TO_TEAM';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
